# Generated by Django 4.2.3 on 2023-08-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_shopping_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
